### ISSUE TITLE
Clarify license and author in Lib/ufoLib/test/testdata/DemoFont.ufo

### ISSUE THREAD

**Issue by medicalwei** [unified-font-object/ufoLib#100]
Sorry @LettError as again I am packaging this for Debian, I have to be careful of copyright attributions.
Although I realize LettError = Erik von Blokland (as stated in LICENSE.txt), it is not obvious in the source code itself.

Could you address this situation by changing the name of the author of the test file?

**Comment by jbicha** [comment]
Specifically, it's this line that should probably match the rest of the project License.

https://github.com/unified-font-object/ufoLib/blob/master/Lib/ufoLib/test/testdata/DemoFont.ufo/fontinfo.plist#L10

**Comment by medicalwei** [comment]
Also this line could be a bit problematic for distributing the code too:
https://github.com/unified-font-object/ufoLib/blob/master/Lib/ufoLib/test/testdata/DemoFont.ufo/fontinfo.plist#L36

"Development release. NOT for distribution." could mean that we cannot redistribute the .ufo along with the package (if that's a legal statement). I believe this is not intentional but please also review this.

**Comment by moyogo** [comment]
I don’t think having the Letterror foundry as the copyright owner is an issue. You wouldn’t ask [large company] to replace the [large company] copyright by the names of the people who did the work.

The "Development release. NOT for distribution." is problematic.

**Comment by medicalwei** [comment]
The problem is not actually the name but the copyright ownership between the project and the test file.
If that's not the same we have to assume they are under a different license and we need to ask you "what license is the test file".

**Comment by LettError** [comment]
I will change the license. Hold your ponies.

**Comment by LettError** [comment]
Let me know if https://github.com/unified-font-object/ufoLib/commit/f726d88bcb04d14e1b2eaa5fb21365a4695eac88 addresses all your licensing and copyright needs.

**Comment by medicalwei** [comment]
Looks good to me. Thank you :)

**Comment by anthrotype** [comment]
https://github.com/unified-font-object/ufoLib/releases/tag/v2.1.1
