### ISSUE TITLE
Appending prefix to "@MMK" kerning group names

### ISSUE THREAD

**Issue by andyclymer** [unified-font-object/ufoLib#118]
Since ``findKnownKerningGroups()`` is able to identify the MetricsMachine "@MMK" prefixes, could it be cleaner if this line in ``convertUFO1OrUFO2KerningToUFO3Kerning()`` replaced the old prefix instead of appending the new prefix to the old group name? 

https://github.com/unified-font-object/ufoLib/blob/37c4777fabf4cd5d1a2dcdf0220907a6495496df/Lib/ufoLib/converters.py#L25

**Comment by LettError** [comment]
Yes, +1 for converting `@MMK_L_xxx` to `@public.kern1_xxx` and  `@MMK_R_xxx` to `@public.kern2_xxx`

**Comment by benkiel** [comment]
Fixed with #122
