### ISSUE TITLE
readGlyphFromString behavior with glyph name

### ISSUE THREAD

**Issue by andyclymer** [unified-font-object/ufoLib#119]
After switching from the robofab.glifLib to the ufoLib.glifLib I've found something unexpected and undocumented, if I provide ``readGlyphFromString()`` with a ``glyphObject`` I don't expect it to change the glyph's name to the one from the .glif file.

Do you think this change was intentional, or should it avoid reading the ``name`` attribute when a glyph object is provided? From the docs it doesn't look like the name should be read:

https://github.com/unified-font-object/ufoLib/blob/37c4777fabf4cd5d1a2dcdf0220907a6495496df/Lib/ufoLib/glifLib.py#L480-L494

Sample code, reading a .glif named "D" into a glyph object named "E" will change the glyph name to "D":

```python
from ufoLib.glifLib import readGlyphFromString
from fontParts.world import NewFont

glifData = """<?xml version="1.0" encoding="UTF-8"?>
<glyph name="D" format="2">
  <advance width="500"/>
  <unicode hex="0044"/>
  <outline>
    <contour>
      <point x="133" y="137" type="line"/>
      <point x="119" y="583" type="line"/>
      <point x="408" y="655" type="line"/>
      <point x="403" y="182" type="line"/>
    </contour>
  </outline>
</glyph>
"""

f = NewFont()
g = f.newGlyph("E")
pen = g.getPointPen()
readGlyphFromString(glifData, glyphObject=g.naked(), pointPen=pen)

print len(g.contours)
print g.name
```

**Comment by typemytype** [comment]
it happens here: https://github.com/unified-font-object/ufoLib/blob/37c4777fabf4cd5d1a2dcdf0220907a6495496df/Lib/ufoLib/glifLib.py#L977-L982

**Comment by typemytype** [comment]
the difficulty is that fontParts objects are slightly different from defcon objects. ufoLib works with an defcon api methods. FontParts is different from conveniency point of view and these are not compatible. 

This is been solved on a fontParts level see https://github.com/robofab-developers/fontParts/pull/113
