### ISSUE TITLE
Why is trailing offCurve in open contour forbidden?

### ISSUE THREAD

**Issue by adrientetar** [unified-font-object/ufoLib#12]
@typesupply: in 69a04a7d7a3f026a80988ce25797ed70237d1371, you changed the GLIF code to fail on trailing offCurve in an open contour where they were previously ignored. Is there any reason for doing this?

Looking at other font editors, while Glyphs does remove any trailing offCurve on mouse-up, robofont does save and open trailing offCurves to UFO &ndash; something which we currently fail on&hellip;

Edit: FontLab VI behaves similarly to Glyphs here.

cc @typemytype

**Comment by typesupply** [comment]
> @typesupply: in 69a04a7, you changed the GLIF code to fail on trailing offCurve in an open contour where they were previously ignored. Is there any reason for doing this?

It has been a long time, but my memory is this: Technically, those off curves don't belong to a segment, so they are strays and uninterpretable. In other words, what exactly do they mean? If there is an implied close path at the end of the contour, if the close path an implied curve segment? If so, where is the second off curve? It's a mess and was causing issues elsewhere, so I banned them. I can't remember if the spec bans them or not, but I suppose that it should.

I remember a bit of a debate about this in RoboFont. In a design environment, that trailing off curve is important within a drawing session. For example, you don't want to have a pen tool clip the off curve at the end of each contour while drawing the contour. But, if you close the font and then open it, the magic off curve should not be there.

If it is raising lots of errors, ufoLib could silently filter them out.

**Comment by adrientetar** [comment]
> If it is raising lots of errors, ufoLib could silently filter them out.

I think this seems reasonable otherwise I'd have to check for these separately, something ufoLib already does on its own.

**Comment by anthrotype** [comment]
with validate=False it will not complain, so I deem this fixed.
