### ISSUE TITLE
XML header changed

### ISSUE THREAD

**Issue by miguelsousa** [unified-font-object/ufoLib#158]
The move to `lxml` library introduced changes to the XML header.

**ufoLib 2.1.1**
```xml
<?xml version="1.0" encoding="UTF-8"?>
```

**ufoLib 2.2.4**
```xml
<?xml version='1.0' encoding='utf-8'?>
```

**Comment by anthrotype** [comment]
We are still in time to fix this (after all, a third release in a week, we can do four).
We can tell lxml to not add the xml_declaration=False, and prepend it ourselves (with double quotes) to the string that lxml generates.
Shall i do it?

**Comment by miguelsousa** [comment]
Let me first test if any other changes were introduced. If they were then there's no point in bending backwards just because of the header.
