### ISSUE TITLE
move test suite outside of Lib/ufoLib?

### ISSUE THREAD

**Issue by anthrotype** [unified-font-object/ufoLib#165]
is there a reason for keeping the tests inside the installed module, and not as an outside "tests" folder?
I would prefer to use the external tests layout. We do that for fonttools and other similar projects. We can add more testdata files (which should not be installed but are required for running the test suite), and also it makes it possible to run the test suite against a different installed version of the package.

**Comment by benkiel** [comment]
Go for it
