### ISSUE TITLE
differences in str(float) between Python 2 and 3

### ISSUE THREAD

**Issue by anthrotype** [unified-font-object/ufoLib#19]
In Python 2, the `str` of a float can be different from its `repr`:

```python
>>> print str(1.4*1.5)
2.1
>>> print repr(1.4*1.5)
2.0999999999999996
```

The algorithm used in Python 2 `str` was to arbitrarily format floats with up to 12 decimal precision -- as in `{:.12g}.format(f)`. On the other hand, `repr` would use 17 significant digits, to ensure that `eval(repr(f)) == f`.

Now, Python 3.1 introduced a new "short representation" for the `repr` of a float which eliminated the main reason for the difference between `str` and `repr`. Consequently, since Python 3.2, `str` and `repr` use the same algorithm, producing the same output:

```python
>>> print(str(1.4*1.5))
2.0999999999999996
>>> print(repr(1.4*1.5))
2.0999999999999996
```

However, even though the new `repr` was backported to Python 2.7, the difference between `repr` and `str` is still present in Python 2.7.

There are several places in ufoLib where float numbers are converted to strings using `str(f)`: see [here](https://github.com/unified-font-object/ufoLib/blob/master/Lib/ufoLib/glifLib.py#L1511-L1512) for example.
Because of that, the output can be different whether one is using Python 2 or Python 3, in that the former uses up to 12 digits (`str(f) != repr(f)`), while the latter uses 17 (`str(f) == repr(f)`).

I think it's a problem if .glif files produced by different python versions using the *same* ufoLib end up with different outputs.

One solution could be to use `repr` instead of `str` to format float numbers, since the former has identical outputs in both 2 and 3. Or alternatively, we can use explicit string formatting as in `{:.17g}.format(f)` to avoid any such confusions.

Any comments?

More info:
http://bugs.python.org/issue9337
http://bugs.python.org/issue1580
http://stackoverflow.com/questions/25898733/why-does-strfloat-return-more-digits-in-python-3-than-python-2

**Comment by moyogo** [comment]
Using `repr` sounds good.

**Comment by adrientetar** [comment]
I like that the old Python repr keeps 2.1 and not 2.0999999999999996 which is noisy, maybe we should keep some rounding?

**Comment by anthrotype** [comment]
Maybe I didn't explain myself well.
`repr` works the same way in both python 2 and 3. It does not do any rounding, it uses the maximum float precision (up to 17 significant digits). It `str` that in python2 uses up to 12 digits, while in python3 it's the same as repr.

would you like to force the old `str` behaviour in both python 2 and 3? I believe the opposite should be the case, ie. making python2 behave like python3.

**Comment by anthrotype** [comment]
besides `2.1 != 2.0999999999999996`, even though you may argue the difference is irrelevant. But when you are comparing floats (e.g. unit tests), you want to be precise.

**Comment by anthrotype** [comment]
In python 2 this occurs:
```python
>>> f = 1.4 * 1.5
>>> eval(str(f)) == f
False
>>> eval(repr(f)) == f
True
```

in python 3, they both return True.

**Comment by anthrotype** [comment]
I think the floating-point tutorial explains the whole issue very nicely: 
https://docs.python.org/3/tutorial/floatingpoint.html

The problem in glifLib is not just the _display_ of float numbers, but the need to be able to roundtrip from python objects to the stringified floats written to a .glif file without losing any data.

Unless the UFO specification puts an arbitrary limit on the maximum float precision that can be encoded in a UFO, which I don't think it's the case, is it?

**Comment by anthrotype** [comment]
Indeed,

> There is no limit to the number of digits before or after the decimal.

https://github.com/unified-font-object/ufo-spec/blob/master/source/versions/ufo3/conventions.html#L56
