### ISSUE TITLE
Zip / tar storage

### ISSUE THREAD

**Issue by behdad** [unified-font-object/ufoLib#23]
@typesupply I know you experimented with one-file options for UFO 4.  Any chance that can be integrated into ufoLib?  One way is to use something like https://pypi.python.org/pypi/fs/0.5.0 and let the user provide a fs instance that is used for file access.

I'm interested in writing to, and reading from, one file.  Zip comes as a natural candidate, but tar might be interesting as well since it does not have the compression/decompression overhead.

**Comment by benkiel** [comment]
See: https://github.com/unified-font-object/ufo4Research

Nothing, as far as I know, has been decided yet. Zip had some drawbacks as an option. If you look in the UFO mailing list, I believe that there was some good discussion about the advantages/drawbacks of all the options. 

If I recall, SQLite may have been the most promising option, but further research is needed.

**Comment by behdad** [comment]
Thanks.

**Comment by LettError** [comment]
@Behdad: does fs 0.5.0 provide an abstract approach to writing to zip?

**Comment by typesupply** [comment]
FYI, I've started a new ufo4 branch of ufoLib to experiment with this. I'm 99.9% sure that I want to go with ZIP over SQLite. SQLite has some really amazing things that I *think* we could use in the future, but it's going to be harder to implement both in the spec and in code in the short term. The things that might be cool in SQLite we could probably do in a package or ZIP if we slightly restructure UFO. So, that's why I'm on the ZIP train now. (Plus, ZIP is the idea I had for a single file UFO structure back in 2003 or 2004!)

@behdad I'll try to implement a version of ufoLib that reads and writes to ZIP in the next few days. If you put this to use in the real world I'd really like to know how ZIP performs. The 0.01% of doubt that I have is that we haven't tested ZIP at scale.

**Comment by benkiel** [comment]
Ah, sorry I had it wrong re: SQLite vs. Zip.

**Comment by graphicore** [comment]
> One way is to use something like https://pypi.python.org/pypi/fs/0.5.0 and let the user provide a fs instance that is used for file access.

My obligatory message from the other side … I'm doing exactly this in ufoJS and I like it :-) It gives me a lot of flexibility. An [IO](https://github.com/graphicore/Atem-IO/tree/master/lib/io) instance (my equivalent to the python fs lib) is passed to the constructors of UFOWriter, UFOReader, GlyphSet etc. as in here: `function UFOWriter(io, path, formatVersion /*default: 3*/, fileCreator /*default: 'org.ufojs.lib'*/)`

You could easily make it a keyword argument and default to the standard fs (`OSFS`) so nothing would change for current users.

The python-fs Module comes with these highlights (in my opinion):
 
* MemoryFS access files & directories stored in memory (non-permanent but very fast)
* MountFS creates a virtual directory structure built from other filesystems
* ZipFS access files and directories contained in a zip file
* OSFS the native filesystem

Note: In my JS version I don't have a ZipFS yet, instead, I write to MemoryFS and copy from there into the zip library once I'm finished. This could be worth a benchmark, depending on how the python ZipFS is implemented and how frequently files are re-read or re-written until the zip is consumed.

MountFS is great tool for application building.

Also, it should be easy to implement a new backend, if it is needed. There's at least a base class http://docs.pyfilesystem.org/en/latest/base.html#fs.base.FS

**Comment by behdad** [comment]
> @Behdad: does fs 0.5.0 provide an abstract approach to writing to zip?

Yes.

Since I'm jetlagged and woke up at 10pm now, I might as well prototype this...

**Comment by typesupply** [comment]
> Since I'm jetlagged and woke up at 10pm now, I might as well prototype this...

Look at the UFO4 research code to see how I plan to switch the file system without higher levels knowing any different.

> The python-fs Module comes with these highlights (in my opinion):

Yeah. I took a quick look at it recently and it's really similar to what I have in mind. I might use fs if mine is too much work to implement. I'm just a bit nervous about adding another dependency if I don't need to.

**Comment by anthrotype** [comment]
There's no problem adding dependencies when they are well maintained (i.e. regularly versioned, hosted on PyPI, etc.). Usually better using "wheels" than reinventing the wheel.

**Comment by typesupply** [comment]
> There's no problem adding dependencies when they are well maintained (i.e. regularly versioned, hosted on PyPI, etc.). Usually better using "wheels" than reinventing the wheel.

Of course. I just don't like to require an additional package if the package just lightly wraps something in the standard lib or if I'm only using a couple of functions.

I've been doing this a long time and watched too many packages cone and go. I'm old.

**Comment by behdad** [comment]
We don't have to add dependency.  For simple files, we can implement a tiny class that fills it in.

**Comment by typesupply** [comment]
Yeah. That's what I was doing in the research tests. Base: https://github.com/unified-font-object/ufo4Research/blob/master/fileStructureTests/core/fileSystem.py ZIP: https://github.com/unified-font-object/ufo4Research/blob/master/fileStructureTests/ufo3zip.py

**Comment by behdad** [comment]
Right.  I have had seen that before.

What do you think about reusing the fs module API?  Then the user can pass in a fs instance and we don't care about the type per se.

**Comment by typesupply** [comment]
The one concern that I had was holding a huge ZipFile in memory during read/write. I took a quick look at fs a few hours ago to see if it smartly handles this. I need to look a little more.

**Comment by behdad** [comment]
I'm guessing that it does.  At any rate, from what I've seen, the gazillion Python objects representing those bytes consume many times more memory.  An order of magnitude at least.

**Comment by typesupply** [comment]
Yeah. I was thinking about doing that very thing. That way fs could be used if available and if not it would still work.

Don't get me wrong, fs looks great. It's just that installing dependencies in Pythin sucks and most UFO users aren't developers so it's extra hard for them. I know we can't solve everything, but you get the idea

**Comment by behdad** [comment]
> Don't get me wrong, fs looks great. It's just that installing dependencies in Pythin sucks and most UFO users aren't developers so it's extra hard for them. I know we can't solve everything, but you get the idea

I'm totally with you there.

**Comment by anthrotype** [comment]
I'm totally not. Installing Python dependencies is automatic and effortless for the user, _if_ developers take the responsibility of packaging their libraries properly. I'm sorry, I didn't want to sidetrack this discussion. ;)

**Comment by behdad** [comment]
> I'm totally not. Installing Python dependencies is automatic and effortless for the user, if developers take the responsibility of packaging their libraries properly. I'm sorry, I didn't want to sidetrack this discussion. ;)

Yes, but the more dependencies you add, the more uncertainty you have to deal with.  Every piece of code has bugs, and thirdparty packages are more likely to be buggy than internal Python modules....  Take the sympy issue we had to deal with recently...

**Comment by anthrotype** [comment]
Safety in numbers, I guess.

**Comment by typesupply** [comment]
One more note for clarity...

> Ah, sorry I had it wrong re: SQLite vs. Zip.

Actually, you had it right. I was pretty certain that I wanted to go with SQLite until a few days ago. I reviewed the nots and research and changed my mind. SQLite has some serious advantages, but ZIP is going to be easier to support. So, sigh, pragmatism.

**Comment by typesupply** [comment]
Update: The ufo4 branch now supports this. The UFO spec hasn't changed so this is still not "legal." It also doesn't work with the ufo3 branch of defcon when calling defcon's font.save. That will be dealt with in defcon later. Anyway...

The change requires fs and I think I'll leave that requirement. fs is very nice and handles some of the rougher parts of interacting with ZIPs. The `UFOReader` API is unchanged. `UFOWriter` has a couple of small API changes:

1. The constructor has a new `structure` argument that defines what type of file structure should be written.
2. The caller *must* call writer.close when a writing session is complete. This is when the ZIP file is finalized, so it is essential.

The implementation is a bit sketchy and the documentation has not been updated. But, hey, it works. We'll build on this as UFO 4 develops more.
