### ISSUE TITLE
Examine speed of XML parsing and interpretation.

### ISSUE THREAD

**Issue by typesupply** [unified-font-object/ufoLib#27]
XML parsing, interpretation and writing is nearly 100% of what ufoLib does. As UFOs get bigger and bigger I think about the speed of all this more and more. We haven't ever really put any significant effort into optimizing ufoLib. I mean, we've tried to be smart about it, but we've never had an official look at speeding things up. Maybe we should.

The readers and writers in ufoLib were designed to be lazy. UFOReader only loads the individual files when needed. UFOWriter only writes files when needed. Anecdotally speaking, writing has never been a speed issue. Reading has. Specifically, this is apparent when an app needs to read _all_ of the glyphs in a UFO during the initial file open. That's the situation that I'm interested in speeding up.

Reading a UFO can be broken into three parts:
1. Parsing the XML.
2. Interpreting and validating the data in the XML.
3. Creating objects with the interpreted data.

Object creation is not something that ufoLib handles directly. It is handled by a system like defcon and _that_ system is responsible for making this part of the process fast. (FWIW, I've optimized the heck out of defcon and I'm out of big ideas over there.) That leaves parsing and interpretation + validation as potential optimization points.

Parsing in ufoLib is handled by xmlTreeBuilder. @justvanrossum wrote this many years ago for use with the newly invented GLIF files. At the time, ElementTree was mostly a twinkling in Effbot's eye and, obviously, it wasn't part of the standard library. Over the last n years I've kicked around the idea of using ElementTree instead of xmlTreeBuilder. A few reasons why I've been interested in this:
1. cElementTree is very fast.
2. The ElementTree API is very nice.
3. ElementTree part of the standard library.
4. ElementTree is code that we don't have to maintain.

One really big reason why I haven't deeply investigated this:
1. xmlTreeBuilder works.

My guess is that the bulk of the time is spent in the interpreting and validating part of the process. GLIF in particular has some complex structures that need to be validated before passing off for object creation. One of the goals of ufoLib was for libraries like defcon to not have to worry that junk data is coming into them. So, there is a lot of validation that we could look into speeding up.

Finally, this is not a huge issue in ufoLib at the moment. In my daily workflow, reading UFOs is an insignificant amount of time. The tools that work with UFOs are generally very stable, so files don't need to be opened repeatedly after crashes. I open a file once, work on it all day and then close it. I'm mostly concerned about the potential speed issues when UFOs start containing lots of layers.

**Comment by typesupply** [comment]
Here's a quickly built, semi-scientific test of different parsers + tree builders. This isolates the testing to just the text parsing, tree construction and tree iteration. IO is not counted in the timing. Likewise, the data is not being interpreted or validated.

1. xmlTreeBuilder
2. cElementTree
3. ElementTree
4. LXML

```python
import os
import time
from cStringIO import StringIO
from xml.etree import cElementTree as cET
from xml.etree import ElementTree as ET
from lxml import etree as lxmlET
from ufoLib.xmlTreeBuilder import buildTree

runCount = 5

# Preload the strings to remove IO from the timing.

rawXML = {}

def readXML(path):
	for fileName in os.listdir(path):
		p = os.path.join(path, fileName)
		if os.path.isdir(p):
			readXML(p)
		else:
			ext = os.path.splitext(fileName)[-1].lower()
			if ext in (".plist", ".glif"):
				f = open(p, "rb")
				text = f.read()
				f.close()
				rawXML[p] = StringIO(text)


path = os.path.dirname(__file__)
path = os.path.join(path, "Source Code Pro-Black.ufo")
readXML(path)

# Test xmlTreeBuilder.

def recurseXMLTB(tree):
	element, attrs, children = tree
	for child in children:
		if isinstance(child, tuple) and len(child) == 3:
			recurseXMLTB(child)

total = 0
for i in range(runCount):
	for text in rawXML.values():
		t = time.time()
		tree = buildTree(text)
		recurseXMLTB(tree)
		total += time.time() - t
		text.seek(0)

print "xmlTreeBuilder |", total / runCount

# Test cElementTree.

def recurseET(obj):
	for element in obj:
		attrib = element.attrib
		text = element.text
		recurseET(element)

total = 0
for i in range(runCount):
	for text in rawXML.values():
		t = time.time()
		tree = cET.parse(text)
		recurseET(tree.getroot())
		total += time.time() - t
		text.seek(0)

print "cElementTree |", total / runCount

# Test ElementTree.

total = 0
for i in range(runCount):
	for text in rawXML.values():
		t = time.time()
		tree = ET.parse(text)
		recurseET(tree.getroot())
		total += time.time() - t
		text.seek(0)

print "ElementTree |", total / runCount

# Test LXML.

total = 0
for i in range(runCount):
	for text in rawXML.values():
		t = time.time()
		tree = lxmlET.parse(text)
		recurseET(tree.getroot())
		total += time.time() - t
		text.seek(0)

print "LXML |", total / runCount
```

When I run this with _Source Code Pro-Black.ufo_ I get these times:

Tree Builder | Time (seconds)
------------ | --------------
xmlTreeBuilder | 0.708045387268
cElementTree | 0.183525323868
ElementTree | 1.36199989319
LXML | 0.251796197891

**Comment by justvanrossum** [comment]
+1 for using cElementTree. (I must say the fact that RF always reads the full UFO to me is very poor design. It makes RF completely unsuitable for large glyph sets.)

**Comment by anthrotype** [comment]
👍  for cElementTree! 
Lxml is also very fast and has lots of cool features, but cET has the advantage of shipping with the standard library.

When I find some spare time, I would also like to try and see if using Cython could bring speed improvements to ufoLib, e.g. in the data interpretation/validation part. The advantage of Cython is that it "feels" like Python (it's a super set, with additional keywords and type declarations), but compiles into fast and portable C code, so one gets the best of both worlds.

**Comment by typesupply** [comment]
> LXML

Yeah, I was curious about that too. I included it in the tree building test above. cElementTree is roughly twice as fast on the files in the test UFO. The results closely match this [analysis](http://lxml.de/performance.html).

> Cython

That would be a good thing to look into. I looked at Pyrex for that same reason a long time ago, but it wasn't a good fit.

I think [here](https://github.com/unified-font-object/ufoLib/blob/master/Lib/ufoLib/glifLib.py#L892) and [here](https://github.com/unified-font-object/ufoLib/blob/master/Lib/ufoLib/glifLib.py#L1012) to [here](https://github.com/unified-font-object/ufoLib/blob/master/Lib/ufoLib/glifLib.py#L1301) are good places to look for optimizations. We should do some basic profiling before we get too deep into it. I'll try to write a little script for that later today.

**Comment by typesupply** [comment]
I wrote a simple profiler for loading glyphs and the results are below. This is using the ufo4 branch of ufoLib and reading _Source Code Pro-Black.ufo_. The data is not populated into any objects. Rather, it is passed to a dummy 

At a quick glance, it all looks pretty efficient. It takes less than a second to load the whole thing. The biggest expense is in the point structure validation and coercion function. We could look at that, but it's only taking 8.24% of the total loading time. I'm not sure how much we can really speed all of this up.

Anyway, the data is below, so you can draw your own conclusions.

These are the stats specifically for the various parts of ufoLib:

ncalls | tottime | percall | filename:lineno(function)
------ | ------- | ------- | -------------------------
1439 | 0.073 | 0.000 | /glifLib.py:1195(_validateAndMassagePointStructures)
28906/6579 | 0.056 | 0.000 | /xmlTreeBuilder.py:86(stripCharacterData)
80850 | 0.037 | 0.000 | /xmlTreeBuilder.py:36(characterDataHandler)
41665 | 0.028 | 0.000 | /glifLib.py:1308(_number)
1549 | 0.019 | 0.000 | /glifLib.py:215(getGLIF)
1439 | 0.014 | 0.000 | /glifLib.py:1079(_buildOutlinePointsFormat1)
33795 | 0.014 | 0.000 | /xmlTreeBuilder.py:31(endElementHandler)
4889/673 | 0.011 | 0.000 | /plistFromTree.py:25(parseElement)
1549 | 0.008 | 0.000 | /glifLib.py:263(readGlyph)
1549 | 0.008 | 0.000 | /xmlTreeBuilder.py:106(buildTree)
33795 | 0.008 | 0.000 | /xmlTreeBuilder.py:27(startElementHandler)
1549 | 0.007 | 0.000 | /glifLib.py:842(_readGlyphFromTreeFormat1)
1221 | 0.006 | 0.000 | /glifLib.py:1088(_buildOutlineComponentFormat1)
6196 | 0.006 | 0.000 | /filesystem.py:132(_fsExists)
1549 | 0.006 | 0.000 | /glifLib.py:798(_stripGlyphXMLTree)
1549 | 0.005 | 0.000 | /glifLib.py:817(_readGlyphFromTree)
1549 | 0.005 | 0.000 | /glifLib.py:809(_glifTreeFromFile)
1542 | 0.004 | 0.000 | /glifLib.py:1026(buildOutlineFormat1)
1549 | 0.004 | 0.000 | /xmlTreeBuilder.py:43(_expatParseFile)
1439 | 0.004 | 0.000 | /glifLib.py:1069(_buildOutlineContourFormat1)
673 | 0.003 | 0.000 | /glifLib.py:987(_readLib)
1549 | 0.003 | 0.000 | /filesystem.py:198(open)
6968 | 0.003 | 0.000 | /glifLib.py:1302(_relaxedSetattr)
6196 | 0.002 | 0.000 | /filesystem.py:169(exists)
1549 | 0.002 | 0.000 | /glifLib.py:974(_readAdvance)
632 | 0.002 | 0.000 | /validators.py:73(genericDictValidator)
10843 | 0.002 | 0.000 | /filesystem.py:93(_fsRootPath)
1549 | 0.002 | 0.000 | /filesystem.py:239(getFileModificationTime)
1549 | 0.002 | 0.000 | /filesystem.py:106(_fsOpen)
1549 | 0.002 | 0.000 | /glifLib.py:967(_readName)
1549 | 0.002 | 0.000 | /filesystem.py:144(_fsGetFileModificationTime)
632 | 0.001 | 0.000 | /validators.py:589(anchorValidator)
673 | 0.001 | 0.000 | /validators.py:973(glyphLibValidator)
1549 | 0.001 | 0.000 | /filesystem.py:136(_fsIsDirectory)
632 | 0.001 | 0.000 | /glifLib.py:1054(_buildAnchorFormat1)
1549 | 0.001 | 0.000 | /filesystem.py:153(joinPath)
673 | 0.001 | 0.000 | /plistFromTree.py:9(readPlistFromTree)
1549 | 0.001 | 0.000 | /xmlTreeBuilder.py:19(__init__)
1549 | 0.001 | 0.000 | /xmlTreeBuilder.py:23(getRoot)
1549 | 0.001 | 0.000 | /glifLib.py:257(_purgeCachedGLIF)
382 | 0.001 | 0.000 | /validators.py:571(anchorsValidator)
1549 | 0.001 | 0.000 | /filesystem.py:172(isDirectory)
673 | 0.000 | 0.000 | /plistFromTree.py:20(parseTree)
673 | 0.000 | 0.000 | /validators.py:19(isDictEnough)
1 | 0.000 | 0.000 | /glifLib.py:373(keys)
1 | 0.000 | 0.000 | /plistFromTree.py:1(<module>)
1 | 0.000 | 0.000 | /plistFromTree.py:18(PlistTreeParser)

The raw stats:

```
         1335901 function calls (1307809 primitive calls) in 0.886 seconds

   Ordered by: internal time, call count

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
     1549    0.077    0.000    0.180    0.000 {built-in method ParseFile}
     1439    0.073    0.000    0.115    0.000 glifLib.py:1195(_validateAndMassagePointStructures)
28906/6579    0.056    0.000    0.068    0.000 xmlTreeBuilder.py:86(stripCharacterData)
     1549    0.047    0.000    0.047    0.000 {method 'read' of '_io.BufferedReader' objects}
    80850    0.037    0.000    0.043    0.000 xmlTreeBuilder.py:36(characterDataHandler)
     9294    0.029    0.000    0.029    0.000 {posix.stat}
    41665    0.028    0.000    0.028    0.000 glifLib.py:1308(_number)
    10843    0.025    0.000    0.115    0.000 __init__.py:165(getsyspath)
     1549    0.022    0.000    0.022    0.000 {dir}
     1549    0.021    0.000    0.021    0.000 {_io.open}
     1549    0.019    0.000    0.364    0.000 glifLib.py:215(getGLIF)
    21686    0.018    0.000    0.018    0.000 {method 'search' of '_sre.SRE_Pattern' objects}
    80850    0.018    0.000    0.061    0.000 pyexpat.c:441(CharacterData)
    26333    0.018    0.000    0.032    0.000 __init__.py:367(<genexpr>)
     1439    0.014    0.000    0.016    0.000 glifLib.py:1079(_buildOutlinePointsFormat1)
    91842    0.014    0.000    0.014    0.000 {isinstance}
    33795    0.014    0.000    0.017    0.000 xmlTreeBuilder.py:31(endElementHandler)
    12392    0.014    0.000    0.020    0.000 posixpath.py:61(join)
   131551    0.013    0.000    0.013    0.000 {method 'append' of 'list' objects}
    74352    0.012    0.000    0.012    0.000 {method 'startswith' of 'str' objects}
     1549    0.012    0.000    0.095    0.000 __init__.py:364(getinfo)
 4889/673    0.011    0.000    0.041    0.000 plistFromTree.py:25(parseElement)
    83102    0.011    0.000    0.011    0.000 {method 'get' of 'dict' objects}
    10843    0.010    0.000    0.030    0.000 base.py:288(validatepath)
    10843    0.010    0.000    0.014    0.000 __init__.py:198(getmeta)
    45405    0.010    0.000    0.010    0.000 {getattr}
    33795    0.009    0.000    0.017    0.000 pyexpat.c:566(StartElement)
    33795    0.009    0.000    0.025    0.000 pyexpat.c:618(EndElement)
12392/10843    0.009    0.000    0.272    0.000 errors.py:254(wrapper)
     1549    0.008    0.000    0.879    0.001 glifLib.py:263(readGlyph)
     1549    0.008    0.000    0.197    0.000 xmlTreeBuilder.py:106(buildTree)
    33795    0.008    0.000    0.008    0.000 xmlTreeBuilder.py:27(startElementHandler)
     4647    0.007    0.000    0.007    0.000 {built-in method fromtimestamp}
    21686    0.007    0.000    0.007    0.000 {method 'startswith' of 'unicode' objects}
     1549    0.007    0.000    0.224    0.000 glifLib.py:842(_readGlyphFromTreeFormat1)
        1    0.007    0.007    0.886    0.886 glif loading profiling.py:40(loadGlyphs)
    10843    0.006    0.000    0.023    0.000 path.py:20(normpath)
     1221    0.006    0.000    0.009    0.000 glifLib.py:1088(_buildOutlineComponentFormat1)
     6196    0.006    0.000    0.113    0.000 filesystem.py:132(_fsExists)
     1549    0.006    0.000    0.063    0.000 glifLib.py:798(_stripGlyphXMLTree)
    10843    0.005    0.000    0.005    0.000 {method 'replace' of 'str' objects}
     1549    0.005    0.000    0.230    0.000 glifLib.py:817(_readGlyphFromTree)
     1549    0.005    0.000    0.276    0.000 glifLib.py:809(_glifTreeFromFile)
     6196    0.005    0.000    0.102    0.000 __init__.py:248(exists)
     6196    0.004    0.000    0.026    0.000 genericpath.py:23(exists)
     1542    0.004    0.000    0.158    0.000 glifLib.py:1026(buildOutlineFormat1)
    10843    0.004    0.000    0.005    0.000 __init__.py:160(_decode_path)
     1549    0.004    0.000    0.188    0.000 xmlTreeBuilder.py:43(_expatParseFile)
     5045    0.004    0.000    0.005    0.000 {method 'join' of 'str' objects}
    46281    0.004    0.000    0.004    0.000 {len}
     1549    0.004    0.000    0.045    0.000 __init__.py:229(open)
     1439    0.004    0.000    0.136    0.000 glifLib.py:1069(_buildOutlineContourFormat1)
    10843    0.004    0.000    0.004    0.000 base.py:235(getmeta)
     4889    0.004    0.000    0.009    0.000 plistlib.py:409(handleBeginElement)
      673    0.003    0.000    0.049    0.000 glifLib.py:987(_readLib)
     4889    0.003    0.000    0.016    0.000 plistlib.py:415(handleEndElement)
    33865    0.003    0.000    0.003    0.000 {method 'strip' of 'unicode' objects}
    21696    0.003    0.000    0.003    0.000 {method 'keys' of 'dict' objects}
    10843    0.003    0.000    0.005    0.000 path.py:140(relpath)
     1549    0.003    0.000    0.125    0.000 filesystem.py:198(open)
    18403    0.003    0.000    0.003    0.000 {method 'pop' of 'dict' objects}
    12392    0.003    0.000    0.003    0.000 {method 'endswith' of 'str' objects}
     6968    0.003    0.000    0.004    0.000 glifLib.py:1302(_relaxedSetattr)
     3496    0.003    0.000    0.005    0.000 plistlib.py:433(getData)
     6196    0.002    0.000    0.116    0.000 filesystem.py:169(exists)
     1549    0.002    0.000    0.006    0.000 glifLib.py:974(_readAdvance)
     9082    0.002    0.000    0.003    0.000 plistlib.py:420(handleData)
      632    0.002    0.000    0.003    0.000 validators.py:73(genericDictValidator)
    10843    0.002    0.000    0.002    0.000 {method 'rstrip' of 'str' objects}
     3496    0.002    0.000    0.002    0.000 {method 'encode' of 'unicode' objects}
    10843    0.002    0.000    0.002    0.000 filesystem.py:93(_fsRootPath)
     1549    0.002    0.000    0.132    0.000 filesystem.py:239(getFileModificationTime)
     1549    0.002    0.000    0.002    0.000 {pyexpat.ParserCreate}
     4077    0.002    0.000    0.002    0.000 plistlib.py:423(addObject)
     1388    0.002    0.000    0.004    0.000 plistlib.py:465(end_integer)
    10843    0.002    0.000    0.002    0.000 {method 'lstrip' of 'str' objects}
    18403    0.002    0.000    0.002    0.000 glif loading profiling.py:27(addPoint)
     1549    0.002    0.000    0.048    0.000 filesystem.py:106(_fsOpen)
     1549    0.002    0.000    0.003    0.000 glifLib.py:967(_readName)
     1549    0.002    0.000    0.021    0.000 __init__.py:356(_stat)
     1549    0.002    0.000    0.099    0.000 filesystem.py:144(_fsGetFileModificationTime)
     4647    0.001    0.000    0.001    0.000 __init__.py:231(<genexpr>)
     1296    0.001    0.000    0.004    0.000 plistlib.py:467(end_real)
     1549    0.001    0.000    0.006    0.000 genericpath.py:46(isdir)
     1549    0.001    0.000    0.022    0.000 __init__.py:252(isdir)
     6968    0.001    0.000    0.001    0.000 {setattr}
      632    0.001    0.000    0.005    0.000 validators.py:589(anchorValidator)
      673    0.001    0.000    0.002    0.000 validators.py:973(glyphLibValidator)
     1549    0.001    0.000    0.024    0.000 filesystem.py:136(_fsIsDirectory)
      632    0.001    0.000    0.003    0.000 glifLib.py:1054(_buildAnchorFormat1)
     1549    0.001    0.000    0.004    0.000 filesystem.py:153(joinPath)
      673    0.001    0.000    0.043    0.000 plistFromTree.py:9(readPlistFromTree)
     1549    0.001    0.000    0.001    0.000 xmlTreeBuilder.py:19(__init__)
     1549    0.001    0.000    0.001    0.000 xmlTreeBuilder.py:23(getRoot)
     1549    0.001    0.000    0.001    0.000 glifLib.py:257(_purgeCachedGLIF)
     1549    0.001    0.000    0.001    0.000 stat.py:40(S_ISDIR)
      382    0.001    0.000    0.005    0.000 validators.py:571(anchorsValidator)
     2390    0.001    0.000    0.001    0.000 {method 'pop' of 'list' objects}
      696    0.001    0.000    0.001    0.000 plistlib.py:444(begin_dict)
     1549    0.001    0.000    0.025    0.000 filesystem.py:172(isDirectory)
     1549    0.001    0.000    0.004    0.000 __init__.py:44(_os_stat)
     1937    0.000    0.000    0.000    0.000 {method 'items' of 'dict' objects}
      674    0.000    0.000    0.001    0.000 plistlib.py:454(begin_array)
     1549    0.000    0.000    0.000    0.000 stat.py:24(S_IFMT)
      812    0.000    0.000    0.002    0.000 plistlib.py:451(end_key)
      673    0.000    0.000    0.041    0.000 plistFromTree.py:20(parseTree)
      673    0.000    0.000    0.000    0.000 plistlib.py:395(__init__)
      673    0.000    0.000    0.000    0.000 validators.py:19(isDictEnough)
      674    0.000    0.000    0.001    0.000 plistlib.py:458(end_array)
      696    0.000    0.000    0.000    0.000 plistlib.py:448(end_dict)
     1020    0.000    0.000    0.000    0.000 {method 'insert' of 'list' objects}
     1221    0.000    0.000    0.000    0.000 glif loading profiling.py:30(addComponent)
     1439    0.000    0.000    0.000    0.000 glif loading profiling.py:21(beginPath)
     1439    0.000    0.000    0.000    0.000 glif loading profiling.py:24(endPath)
       23    0.000    0.000    0.000    0.000 plistlib.py:463(end_false)
        1    0.000    0.000    0.000    0.000 glifLib.py:373(keys)
        1    0.000    0.000    0.000    0.000 plistFromTree.py:1(<module>)
        1    0.000    0.000    0.886    0.886 <string>:1(<module>)
        1    0.000    0.000    0.000    0.000 six.py:184(find_module)
        1    0.000    0.000    0.000    0.000 plistFromTree.py:18(PlistTreeParser)
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
```

The script:

```python
import sys
import os
import cProfile
from cStringIO import StringIO
import re
import pstats
from ufoLib import UFOReader

class DummyGlyph(object):

	name = None
	width = None
	height = None
	unicodes = None
	note = None
	lib = None
	image = None
	guidelines = None
	anchors = None

	def beginPath(self):
		pass

	def endPath(self):
		pass

	def addPoint(self, *args, **kwargs):
		pass

	def addComponent(self, *args, **kwargs):
		pass


path = os.path.dirname(__file__)
path = os.path.join(path, "Source Code Pro-Black.ufo")
reader = UFOReader(path)

glyphSet = reader.getGlyphSet()

def loadGlyphs():
	for name in glyphSet.keys():
		glyph = DummyGlyph()
		glyphSet.readGlyph(name, glyph, glyph)

# profile

p = cProfile.Profile(builtins=True)
p.run("loadGlyphs()")

# gather stats

f = StringIO()
s = pstats.Stats(p, stream=f)
s.sort_stats("tottime", "ncalls")
s.print_stats()
text = f.getvalue()

# format the stats for github

fileName = os.path.basename(__file__)
pattern = re.compile(
	"\s*"
	"([\S]+)" # ncalls
	"\s+"
	"(\S+)" # totime
	"\s+"
	"(\S+)" # percall
	"\s+"
	"(\S+)" # cumtime
	"\s+"
	"(\S+)" # percall
	"\s+"
	"([\s\S]+)" # location
)

print "ncalls | tottime | percall | filename:lineno(function)"
print "------ | ------- | ------- | -------------------------"

for line in text.splitlines():
	if fileName in line:
		pass
	elif "ufoLib" in line:
		m = pattern.match(line)
		ncalls = m.group(1)
		totime = m.group(2)
		tpercall = m.group(3)
		cumtime = m.group(4)
		cpercall = m.group(5)
		location = m.group(6)
		location = location.split("ufoLib")[-1]
		print " | ".join((ncalls, totime, tpercall, location))

print
print

f.seek(0)
f.truncate(0)
s.strip_dirs()
s.sort_stats("tottime", "ncalls")
s.print_stats()
text = f.getvalue()

print "```"
print text.rstrip()
print "```"
```

**Comment by adrientetar** [comment]
> I wrote a simple profiler for loading glyphs

But you're doing the same thing with all of them. Using xmlTreeBuilder you need to call stripCharacterData() _stripGlyphXMLTree() which is unneeded with ElementTree. Working on patch.

**Comment by anthrotype** [comment]
I think by now we did all the optimization suggested (switching to cElementTree and optionaly to lxml, allowing to disable validation). We can close this.
