### ISSUE TITLE
Prepare 2.0.0 release

### ISSUE THREAD

**Issue by anthrotype** [unified-font-object/ufoLib#46]
I'd like to tag 2.0.0 and publish the wheel/sdist to PyPI.
If you have any patches that you'd like to submit first, or you think we should wait for any outstanding issues to be fixed before the release, please let me know.
I guess the change log could just read "First public release with UFO3 support" or something like that.

**Comment by typesupply** [comment]
I don't have any known issues other than desired enhancements. I'd like to have the final reviews of #26 done soon so that we can move forward with UFOZ or whatever I called it. That can be a 2.1 release though.

**Comment by anthrotype** [comment]
ok, I'll proceed with the 2.0.0 release then.
I'll have to push some temporary tags in order to test out the automatic deployment to Github and PyPI, so please ignore them. I'll get rid of them once I set everything up.

**Comment by anthrotype** [comment]
Ok, done. Version 2.0.0 is now live on PyPI:
https://pypi.python.org/pypi/ufoLib
https://pypi.org/project/ufoLib/

as well as on Github Releases, just because:
https://github.com/unified-font-object/ufoLib/releases/latest

You can now use pip to install/upgrade ufoLib.
