### ISSUE TITLE
Error if glyph.width is a long.

### ISSUE THREAD

**Issue by petrvanblokland** [unified-font-object/ufoLib#52]
In rare occasions the width of a glyph ends up being a long instead one of int or float.
I suspect it happens when you multiple first by a big number and then divide, e.g. in case the width is 
calculated from an interactive tool that shows a scaled glyph and width, and then scales back.
In that situation the font won’t save in RoboFont - shows an error message instead, without telling
which glyph is the problem – which can be annoying when in the middle of editing.

This script will at least helps to cast the widths to int values, so the font can be saved.
(Note that the glyph.width = 0 setting is necessary, or otherwise RF will not notice that it changed.
In that case it will not make the long—>int change happen).

f = CurrentFont()

for g in f:
    if isinstance(g.width, long):
        print g.name, g.width
        w = g.width
        g.width = 0
        g.width = int(w)

![screen shot 2017-01-20 at 21 12 39](https://cloud.githubusercontent.com/assets/377281/22165534/9dcc93ce-df5c-11e6-89a0-60725da4a8b4.png)

**Comment by anthrotype** [comment]
Fixed with https://github.com/unified-font-object/ufoLib/commit/69e63dd4bc73b7299162161f7c11a9655e722277
