### ISSUE TITLE
configure Github email notifications on pushes?

### ISSUE THREAD

**Issue by anthrotype** [unified-font-object/ufoLib#57]
It'd be nice if other developers could subscribe to receive email notifications whenever someone pushes directly to master.

https://help.github.com/articles/managing-notifications-for-pushes-to-a-repository/#enabling-email-service-notifications-for-pushes-to-your-repository

We could send these emails to `fontmake-dev@googlegroups.com` where we also forward similar notifications from the rest of fontmake's dependencies.

I know that defcon isn't just fontmake's dependency, but Github allows to configure up to two forwarding addresses for this purpose, so there would still be one slot left in case you wish to also direct them elsewhere.

Doing this requires admin rights, so I think only @typesupply could set this up.

**Comment by typesupply** [comment]
> Doing this requires admin rights, so I think only @typesupply could set this up.

Sure. Do you know where I do this in the admin?

**Comment by anthrotype** [comment]
oh, same for `defcon` and `fontMath`

**Comment by anthrotype** [comment]
the link above contains the instructions

**Comment by typesupply** [comment]
Done.

**Comment by anthrotype** [comment]
Thank you Tal!
