### ISSUE TITLE
Move ufoLib into fonttools?

### ISSUE THREAD

**Issue by brawer** [unified-font-object/ufoLib#58]
What would you think of moving the ufoLib codebase into fonttools as `fontTools.ufoLib`?

Currently, the broader set of font-related Python libraries is quite a zoo. The resulting dependency hell is not the end of the world, and bots like [pyup.io](https://pyup.io/) are helpful. Still, it currently takes a lot of time to keep the various dependencies up to date; also, the overall complexity is quite mind-boggling. If ufoLib was part of fonttools, other libraries would have one less dependency to care about (and could perhaps be merged into fonttools too). Moving ufoLib to fonttools might also make it possible for fonttools to eventually treat UFO like a normal file format, for example in TTX.

**Comment by behdad** [comment]
Cosimo and I discussed it tonight.  I let him comment.

**Comment by madig** [comment]
@anthrotype: Let's hear it :)

**Comment by anthrotype** [comment]
this is happening https://github.com/fonttools/fonttools/issues/1095
