### ISSUE TITLE
PointPen protocol and identifiers

### ISSUE THREAD

**Issue by anthrotype** [unified-font-object/ufoLib#62]
I was wondering is whether the `AbstractPointPen` interface in `ufoLib.pointPen` should be modified so that all pointpens subclasses must accept an `identifier` keyword argument for `beginPath`, `addPoint` and `addComponent` methods.

That is what the updated `ReverseContourPointPen` in defcon(https://github.com/typesupply/defcon/commit/ea38ad2578bf58d25d366875cb4e8322ac303a7e), and also the `GLIFPointPen` in `ufoLib.glifLib` already do.

Is this some sort of private PointPen protocol 2.0?
If so, I think we could formalize it a bit.
Or maybe it is already and I'm just missing something.

/cc @typesupply @typemytype

**Comment by anthrotype** [comment]
I just realised `glifLib` is already sending out `DeprecationWarning`s when a pointpen does not accept `identifier` keyword arguments, so this is definitely a *thing*.

**Comment by typesupply** [comment]
This is probably just an oversight. It's not anything private.
