### ISSUE TITLE
why raise an error while saving to UFO2 on renaming layer?

### ISSUE THREAD

**Issue by typemytype** [unified-font-object/ufoLib#91]
It should just use the default layer to write data to UFO2

see https://github.com/unified-font-object/ufoLib/blob/master/Lib/ufoLib/__init__.py#L1093-L1094

**Comment by typemytype** [comment]
the same for deleting glyph sets

see https://github.com/unified-font-object/ufoLib/blob/master/Lib/ufoLib/__init__.py#L1132-L1133

both rename as deleting glyphs set should be ignored for anything below formatVersion 3 as it only requires a default glyph set

**Comment by typemytype** [comment]
vice versa setting `setKerningGroupConversionRenameMaps` with formatVersion 3 or higher does not raise an error but silently does nothing

see https://github.com/unified-font-object/ufoLib/blob/master/Lib/ufoLib/__init__.py#L794-L795

**Comment by anthrotype** [comment]
@typemytype can we close this now that you fixed it with 627f997?
