### ISSUE TITLE
ufoLib error writing public.glyphOrder if glyph names are unicode rather than utf-8

### ISSUE THREAD

**Issue by jvgaultney** [unified-font-object/ufoLib#98]
ufoLib gives an error when writing public.glyphOrder if glyph names in the list are unicode rather than utf-8.
(first reported as a bug in glyphsLib, but was told that ufoLib should be able to handle glyph names as unicode without needing to encode them as utf-8)

```
Traceback (most recent call last):
  File "/usr/local/bin/psfglyphs2ufo", line 9, in <module>
    load_entry_point('pysilfont==1.1.3', 'console_scripts', 'psfglyphs2ufo')()
  File "build/bdist.macosx-10.12-intel/egg/silfont/scripts/psfglyphs2ufo.py", line 21, in cmd
  File "build/bdist.macosx-10.12-intel/egg/silfont/core.py", line 505, in execute
  File "build/bdist.macosx-10.12-intel/egg/silfont/scripts/psfglyphs2ufo.py", line 19, in doit
  File "/Tools/glyphsLib/Lib/glyphsLib/__init__.py", line 103, in build_masters
    write_ufo(ufo, master_dir)
  File "/Tools/glyphsLib/Lib/glyphsLib/util.py", line 41, in write_ufo
    ufo.save(out_path)
  File "/Library/Python/2.7/site-packages/defcon/objects/font.py", line 744, in save
    self._saveLib(writer=writer, saveAs=saveAs, progressBar=progressBar)
  File "/Library/Python/2.7/site-packages/defcon/objects/font.py", line 838, in _saveLib
    self.saveLib(writer)
  File "/Library/Python/2.7/site-packages/defcon/objects/font.py", line 855, in saveLib
    writer.writeLib(libCopy)
  File "/Library/Python/2.7/site-packages/ufoLib/__init__.py", line 935, in writeLib
    raise UFOLibError(message)
ufoLib.UFOLibError: public.glyphOrder is not properly formatted.
```

**Comment by anthrotype** [comment]
what is the type of the strings in your `ufo.lib["public.glyphOrder"]`?
Is it `str` or `unicode` (python 2)?
Or are you're using Python 3? In which case, is it `bytes` or `str`?

I might have misunderstood the issue. Initially I thought it was because ufoLib was failing with unicode/str and because it was expecting bytes string, whereas it appears the opposite is the case, at least on python3: fontLibValidator fails if the strings are bytes strings; on python2, it seems to accept either bytes or unicode strings.

https://github.com/unified-font-object/ufoLib/commit/25c84dcb841c32b125b3490c160ed34d22be8b60
https://travis-ci.org/unified-font-object/ufoLib/jobs/290046879

**Comment by adrientetar** [comment]
The build you're showing failed it seems. annoying that these validators don't yield the actual exception.

**Comment by anthrotype** [comment]
yes, it failed, didn't properly test on my local machine.

so what shall we do: allow either bytes or unicode on _both_ python 2 and 3, or only allow unicode or both, or leave it as we do now, allow either unicode or bytes on python 2 and only allow str on python 3?

**Comment by anthrotype** [comment]
> annoying that these validators don't yield the actual exception.

yes, I'll make the error message less generic

**Comment by justvanrossum** [comment]
Bytes seems silly for glyph names. Allow str and unicode on Py2, str on Py3. Is that what it does now?

**Comment by anthrotype** [comment]
yes, this is what it does now. if glyphsLib is sending bytes when on python3, then it's their (mine? :) bug...

**Comment by adrientetar** [comment]
> glyphsLib is sending bytes

But the bytes type in python 2 is str, which we allow now (basestring is str or unicode in python 2). I'm confused, what is the issue here?

**Comment by anthrotype** [comment]
> what is the issue here?

that's what I'm still trying to figure out :grimacing:

**Comment by anthrotype** [comment]
I reverted the failing docstring without changing the current behavior, and also made the error a bit more verbose:

https://github.com/unified-font-object/ufoLib/commit/9c72e09e18bd75fd2ad493d2f13937716871e9d4

I still haven't been able to replicate the issue from glyphsLib though. I'll try again tomorrow.

**Comment by jvgaultney** [comment]
Here's the .glyphs file that's throwing the error:

https://drive.google.com/file/d/0B_VliwmoXu2hMUY3WmY5QWdqTWM/view?usp=sharing

I've updated to the most recent commit of both glyphsLib and ufoLib and now get this error:

`ufoLib.UFOLibError: public.glyphOrder is not properly formatted: expected basestring, found float
`

So maybe this is a glyphLib problem after all?

**Comment by anthrotype** [comment]
oh! Then it's the same bug as the "infinity" glyph name being read as a float instead of a string
https://github.com/googlei18n/glyphsLib/issues/236
It should be fixed now, we can close this.
